stub

diff --git a/src/winetricks b/src/winetricks
--- a/src/winetricks
+++ b/src/winetricks
@@ -13254,7 +13254,8 @@ load_allfonts()
 
 #----------------------------------------------------------------
 
-w_metadata wineappimagebuilder tools \
+# TODO: Add tools metadata
+w_metadata wineappimagebuilder apps \
     title="WINE AppImage builder" \
     publisher="Kreyren" \
     year="2019" \
@@ -13263,23 +13264,78 @@ w_metadata wineappimagebuilder tools \
 load_wineappimagebuilder()
 {
   # Get wine source
-  target="/home/kreyren/appimage_test"
-  [ ! -e "$target" ] && { mkdir "$target" || w_die "Unable to make '$target'" ;} || debug "Directory '$target' already exists"
+  # STUB: use $WINETRICKS_WORKDIR for workdir
 
-  [ ! -e "$target/build" ] && { mkdir "$target/build" || w_die "mkdir failed to make a new directory in '$target/build'" ; } || debug "Directory '$target/build' already exists"
+  # TODO: make MR to Winetricks
+  w_check_exec() {
+    if ! command -v "$1" >/dev/null; then
+      [ -n "$2" ] && printf "Command '%s' is not executable" "$1" || printf '%s\n' "$2"
+    elif command -v "$1" >/dev/null; then w_debug "Command '$1' is executable"
+    fi
+  }
 
-  [ ! -e "$HOME/.cache/$W_PACKAGE/" ] && { mkdir "$HOME/.cache/$W_PACKAGE/" || w_die "Unable to make a new directory in '$HOME/.cache/$W_PACKAGE/'" ;} || debug "Created a new directory in '$HOME/.cache/$W_PACKAGE/'"
+  WINETRICKS_WORKDIR="/home/kreyren/testing_wine"
+  # Credit: https://stackoverflow.com/a/18963118
+  gcc_optimization() { gcc -### -E - -march=native 2>&1 | sed -r '/cc1/!d;s/(")|(^.* - )|( -mno-[^\ ]+)//g' ;}
 
-  [ ! -e "$HOME/.cache/$W_PACKAGE/wine-4.17.tar.xz" ] && (wget 'https://dl.winehq.org/wine/source/4.x/wine-4.17.tar.xz' -O "$HOME/.cache/$W_PACKAGE/wine-4.17.tar.xz" || w_die "wget failed to fetch 'https://dl.winehq.org/wine/source/4.x/wine-4.17.tar.xz' in '$target/build/wine-4.17.tar.xz'") || debug 'wine tarball source already exists'
+  # Abstract: Make compilation as fast as possible for those using it
+  export COMMON_FLAGS="`gcc_optimization` --pipe"
+  export CFLAGS="$COMMON_FLAGS"
+  export CXXFLAGS="$COMMON_FLAGS"
+  export FCLAGS="$COMMON_FLAGS"
+  export FFLAGS="$COMMON_FLAGS"
+  export FCFLAGS="$COMMON_FLAGS"
 
-  [ ! -e "$target/build/wine-4.17" ] && { mkdir "$target/build/wine-4.17" || w_die "failed to make a new directory in '$target/build/wine-4.17" ;} || debug "Directory '$target/build/wine-4.17' already exists"
+  # Fetch WINE source
+  # TODO: Allow fetching different versions of WINE
+  [ ! -e "$W_CACHE/$W_PACKAGE/wine-4.17.tar.xz" ] && w_download 'https://dl.winehq.org/wine/source/4.x/wine-4.17.tar.xz'
 
-  [ ! -e "$target/build/wine-4.17/LICENSE" ] && tar -xf "$HOME/.cache/$W_PACKAGE/wine-4.17.tar.xz" -C "$target/build/"
+  [ ! -e "$WINETRICKS_WORKDIR/wine-4.17" ] && { mkdir "$WINETRICKS_WORKDIR/wine-4.17" || w_die "failed to make a new directory in '$WINETRICKS_WORKDIR/wine-4.17" ;} || w_debug "Directory '$WINETRICKS_WORKDIR/wine-4.17' already exists"
+
+  [ ! -e "$WINETRICKS_WORKDIR/wine-4.17/LICENSE" ] && tar -xf "$W_CACHE/$W_PACKAGE/wine-4.17.tar.xz" -C "$WINETRICKS_WORKDIR/"
+
+    # Compile WINE
+  ## TODO: Logic for compilation of WINE
+  w_check_exec 'flex'
+  w_check_exec 'bison'
+  w_check_exec 'make'
+  # TODO: Enable win64 on demand
+  ## We are fetching wine from official release -> no regression tests needed
+  (
+    # TODO: Avoid using cd
+    w_try_cd "$WINETRICKS_WORKDIR/wine-4.17"
+    [ ! -e "$WINETRICKS_WORKDIR/wine-4.17/Makefile" ] && w_try "$WINETRICKS_WORKDIR/wine-4.17/configure" --disable-tests --srcdir="$WINETRICKS_WORKDIR/wine-4.17/" --enable-win64
+  )
+  # TODO: Apply patches
+  [ ! -e "$WINETRICKS_WORKDIR/wine-4.17/libs/wine/libwine.so.1.0" ] && w_warn "We are about to compile whole WINE, this is going to take some time.." && w_try make -C "$WINETRICKS_WORKDIR/wine-4.17/" "$([ -n "$(nproc)" ] && echo "-j$(nproc)")"
 
   # Get appimagetool
-  [ ! -e "$HOME/.cache/$W_PACKAGE/appimagetool-x86_64.AppImage" ] && wget 'https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage' -O "$target/build/appimagetool-x86_64.AppImage"
-  [ ! -e "$target/build/appimagetool-x86_64.AppImage" ] && [ -e "$HOME/.cache/$W_PACKAGE/appimagetool-x86_64.AppImage" ] && cp "$HOME/.cache/$W_PACKAGE/appimagetool-x86_64.AppImage" "$target/build/"
-  [ ! -x "$target/build/appimagetool.AppImage" ] && chmod +x "$target/build/appimagetool-x86_64.AppImage"
+  [ ! -e "$W_CACHE/$W_PACKAGE/appimagetool-x86_64.AppImage" ] && w_download 'https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage'
+  [ ! -e "$WINETRICKS_WORKDIR/appimagetool.AppImage" ] && [ -e "$W_CACHE/$W_PACKAGE/appimagetool-x86_64.AppImage" ] && cp -r "$W_CACHE/$W_PACKAGE/appimagetool-x86_64.AppImage" "$WINETRICKS_WORKDIR"
+  [ ! -x "$WINETRICKS_WORKDIR/appimagetool.AppImage" ] && { chmod +x "$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage" || w_die "Unable to set executable permissions on '$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage'" ;} || w_debug "File '$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage' is already executable"
+
+
+  ## Export in workdir
+  [ ! -e "$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage" ] && [ -e "$W_CACHE/$W_PACKAGE/appimagetool-x86_64.AppImage" ] && cp "$W_CACHE/$W_PACKAGE/appimagetool-x86_64.AppImage" "$WINETRICKS_WORKDIR/"
+  [ ! -x "$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage" ] && chmod +x "$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage"
+
+  # Build AppImage
+  (
+    w_try_cd "$WINETRICKS_WORKDIR"
+    [ ! -e "$WINETRICKS_WORKDIR/squashfs-root/AppRun" ] && w_try "$WINETRICKS_WORKDIR/appimagetool-x86_64.AppImage" --appimage-extract
+  )
+
+  # Make appimage executable
+  [ ! -x "$WINETRICKS_WORKDIR/squashfs-root/AppRun" ] && chmod +x "$WINETRICKS_WORKDIR/squashfs-root/AppRun"
+
+  # Configure AppImage
+  [ ! -e "$WINETRICKS_WORKDIR/wine-4.17/" ] && { cp "$WINETRICKS_WORKDIR/squashfs-root/AppRun" "$WINETRICKS_WORKDIR/wine-4.17/" || w_die "Unable to copy '$WINETRICKS_WORKDIR/squashfs-root/AppRun' to '$WINETRICKS_WORKDIR/wine-4.17/'" ;}
+  [ ! -e "$WINETRICKS_WORKDIR/wine-4.17/appimagetool.desktop" ] && { cp "$WINETRICKS_WORKDIR/squashfs-root/appimagetool.desktop" "$WINETRICKS_WORKDIR/wine-4.17/" || die "Unable to copy '$WINETRICKS_WORKDIR/squashfs-root/appimagetool.desktop' to '$WINETRICKS_WORKDIR/wine-4.17/'" ;}
+
+  (
+    export ARCH='x86_64'
+    [ -e "$WINETRICKS_WORKDIR/wine-4.17/AppRun" ] && "$WINETRICKS_WORKDIR/wine-4.17/AppRun" -v "$WINETRICKS_WORKDIR/wine-4.17/" -u "gh-releases-zsync|$USER|Wine_Appimage|winetricks|wine-*winetricks.AppImage.zsync" "$W_PACKAGE.AppImage"
+  )
 }
 
 #######################
